name: ITMO Check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache
        uses: actions/cache@v4
        with:
          path: itmo_data.json
          key: itmo-data-${{ github.run_id }}
          restore-keys: |
            itmo-data-
      - name: Install
        run: pip install requests
      - name: Run
        run: python monitor.py
